### ISSUE TITLE
请考虑一下支持WebSphere Application Server 以及 tomcat5的版本，谢谢

### ISSUE THREAD

**Issue by christinkaka** [uavorg/uavstack#115]
目前看支持中间件中没有WebSphere Application Server，tomcat5 以及tomcat6.0.32版本也时有一定的适配问题，请帮忙看看是否可以支持，谢谢

**Comment by uavstack** [comment]
Thanks for issue us. this is an important issue for us, we will discuss that soon

**Comment by zxzxzczz** [comment]
Hi,

能简单说说WAS，Tomcat5， Tomcat 6.0.32等的大致量级以及版本分布情况吗？
如果不方便在GitHub，可以mail到uavstacksupport@163.com
