### ISSUE TITLE
tomcat中定义虚拟访问路径时，mof植入会失败。请帮忙看看，谢谢

### ISSUE THREAD

**Issue by christinkaka** [uavorg/uavstack#126]
通过在server.xml中增加context字段定义虚拟访问路径，启动无问题，但是mof会在catalina.out中打印异常。请帮忙分析一下，谢谢

**Comment by zxy0728** [comment]
Can you describe this exception in detail or the exception log? It will help us to locate the source of the ex. Thx!

**Comment by christinkaka** [comment]
有无联系邮箱，我把日志发你吧

在2017年12月26日 10:28，xinyuzhou1 写道： Can you describe this exception in detail or the exception log? It will help us to locate the source of the ex. Thx!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/uavorg/uavstack","title":"uavorg/uavstack","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/uavorg/uavstack"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zxy0728 in #126: Can you describe this exception in detail or the exception log? It will help us to locate the source of the ex. Thx!"}],"action":{"name":"View Issue","url":"https://github.com/uavorg/uavstack/issues/126#issuecomment-353905974"}}}

**Comment by zxy0728** [comment]
Email: zxy0728114@163.com.    
Please send me your log. THANK you!

**Comment by ieven** [comment]
https://github.com/uavorg/uavstack/pull/144 这个merge应该能解决您遇到的问题。您可下载最新的uav代码自行编译或从官网下载mof进行更新并验证。再次感谢您对UAV的大力支持。

**Comment by Charliemao** [comment]
你们有没有遇到编译不过的错误呢？#136
[INFO] com.creditease.uav.monitorframework.agent .......... FAILURE [ 0.205 s]
[INFO] com.creditease.uav.hook.dubbo ...................... SKIPPED
[INFO] com.creditease.uav.jetty.plus.core ................. SKIPPED
[INFO] com.creditease.uav.monitorframework.buildComponent . SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ---------------------
......
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project com.creditease.uav.monitorframework.agent: Compilation failure: Compilation failure:
[ERROR] ../uavstack/com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/mscp/plus/MSCPProfileHandler.java:[95,60] 找不到符号
[ERROR] 符号: 方法 loadClassFromFeatureClassLoaders(java.lang.String)
[ERROR] 位置: 接口 com.creditease.agent.spi.IConfigurationManager
[ERROR]
../uavstack/com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/mscp/plus/MSCPProfileHandler.java:[237,76] 找不到符号
[ERROR] 符号: 方法 getFeatureClassLoader()
[ERROR] 位置: 接口 com.creditease.agent.spi.IConfigurationManager
[ERROR] -> [Help 1]

从master pull最新的代码仍然报上述错误？

**Comment by zxzxzczz** [comment]
源代码不是最新的，请和master同步一下，再编译。loadClassFromFeatureClassLoaders这个方法是增加优化feature隔离机制时候增加的方法
