### ISSUE TITLE
编译中间件增强框架（MOF探针）失败 

### ISSUE THREAD

**Issue by Charliemao** [uavorg/uavstack#136]
有没有人编译时遇到下面的问题呢？

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] ../uavstack/com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/mscp/plus/MSCPProfileHandler.java:[95,60] 找不到符号
  符号:   方法 loadClassFromFeatureClassLoaders(java.lang.String)
  位置: 接口 com.creditease.agent.spi.IConfigurationManager
[ERROR] ../uavstack/com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/mscp/plus/MSCPProfileHandler.java:[237,76] 找不到符号
  符号:   方法 getFeatureClassLoader()
  位置: 接口 com.creditease.agent.spi.IConfigurationManager
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] com.creditease.uav.fastjson ........................ SUCCESS [ 23.498 s]
[INFO] com.creditease.uav.helper .......................... SUCCESS [ 11.467 s]
[INFO] com.creditease.uav.annoscan ........................ SUCCESS [  6.113 s]
[INFO] com.creditease.uav.logging ......................... SUCCESS [  4.702 s]
[INFO] com.creditease.uav.ttl ............................. SUCCESS [ 39.235 s]
[INFO] com.creditease.uav.monitorframework ................ SUCCESS [ 12.241 s]
[INFO] com.creditease.uav.tomcat.plus.core ................ SUCCESS [  5.189 s]
[INFO] com.creditease.uav.mock.sl4j ....................... SUCCESS [  3.471 s]
[INFO] com.creditease.uav.monitorframework.dproxy ......... SUCCESS [  4.073 s]
[INFO] com.creditease.uav.monitorframework.apm ............ SUCCESS [  6.631 s]
[INFO] com.creditease.uav.loghook ......................... SUCCESS [  4.197 s]
[INFO] com.creditease.uav.hook.httpclients ................ SUCCESS [  6.117 s]
[INFO] com.creditease.uav.hook.jdbc ....................... SUCCESS [ 15.560 s]
[INFO] com.creditease.uav.hook.jaxws ...................... SUCCESS [  3.895 s]
[INFO] com.creditease.uav.hook.redis ...................... SUCCESS [  4.649 s]
[INFO] com.creditease.uav.hook.mongoclients ............... SUCCESS [  4.296 s]
[INFO] com.creditease.uav.hook.mq ......................... SUCCESS [  5.466 s]
[INFO] com.creditease.uav.monitorframework.agent .......... FAILURE [  0.205 s]
[INFO] com.creditease.uav.hook.dubbo ...................... SKIPPED
[INFO] com.creditease.uav.jetty.plus.core ................. SKIPPED
[INFO] com.creditease.uav.monitorframework.buildComponent . SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ---------------------
......
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project com.creditease.uav.monitorframework.agent: Compilation failure: Compilation failure:
[ERROR] ../uavstack/com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/mscp/plus/MSCPProfileHandler.java:[95,60] 找不到符号
[ERROR] 符号:   方法 loadClassFromFeatureClassLoaders(java.lang.String)
[ERROR] 位置: 接口 com.creditease.agent.spi.IConfigurationManager
[ERROR] 
../uavstack/com.creditease.uav.monitorframework.agent/src/main/java/com/creditease/uav/mscp/plus/MSCPProfileHandler.java:[237,76] 找不到符号
[ERROR] 符号:   方法 getFeatureClassLoader()
[ERROR] 位置: 接口 com.creditease.agent.spi.IConfigurationManager
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :com.creditease.uav.monitorframework.agent

**Comment by zxzxzczz** [comment]
IConfigurationManager.loadClassFromFeatureClassLoaders这个是很早之前增强MSCP feature隔离性时后新增的方法，看起来代码不是很同步，请与uavstack master代码同步一下，从master拉pull request到你的github profile。

另外，社区刚刚发布了UAVStackIDE和搭建手册，可以使用这个搭建UAVStack开发环境。下载地址：https://pan.baidu.com/s/1o81LNS2

**Comment by Charliemao** [comment]
pull request地址是什么能发一下吗？

**Comment by Charliemao** [comment]
拿12.29release的代码仍然是编不过，是不是master没有合并？ @zxzxzczz
