### ISSUE TITLE
服务流调用访问次数统计需求

### ISSUE THREAD

**Issue by ZHANGGUOQING91** [uavorg/uavstack#19]
uav全体：
      您好，关于服务图谱中服务流调用访问次数的需求，目前只支持单个实例的访问次数统计，还有单个实例的总访问次数。但是更重要的是对于整个集群来说，意义更为重大！
      需求：增加 集群总调用访问次数，历史访问总次数，同比环比错误率统计，实例同比环比错误率统计。
      此需求价值更为重大，希望考虑增加！

**Comment by uavstack** [comment]
Hi,
Thanks for submit new requirement. some questions shoule be clarified. those helps us to understand your expectation.
Q1: 集群总调用访问次数，历史访问总次数 这个在全局视图有的。是希望在服务图谱里面也体现？可以详细一些
Q2: 同比错误率率统计请详细说明一下期望？你们的应用场景期望
Q3: 环比错误率统计请详细说名一下期望？特别环比时间，你们的应用场景期望

**Comment by zxzxzczz** [comment]
Hi ZHANGGUOQING91,
能否帮助我们解读一下的你需求的细节。
Q1: 集群总调用访问次数，历史访问总次数 这个在全局视图有的。是希望在服务图谱里面也体现？可以详细一些
Q2: 同比错误率率统计请详细说明一下期望？你们的应用场景期望
Q3: 环比错误率统计请详细说名一下期望？特别环比时间，你们的应用场景期望

**Comment by ZHANGGUOQING91** [comment]
您好
A1：总调用次数存在，不需要在服务图谱展示了。
A2、A3：比如 按时间段查询 此阶段错误与上时间阶段内的错误数同比环比率

**Comment by uavstack** [comment]
should we close this issue, seems we have done this issue for open source version

**Comment by ZHANGGUOQING91** [comment]
ok ,thanks
