### ISSUE TITLE
应用集群分组混乱

### ISSUE THREAD

**Issue by gameboy120** [uavorg/uavstack#204]
同一台机器上启动了多个tomcat进程，多个应用的web.xml的displayname名字被识别并通过逗号分割后放到一个应用集群。
![tomcat-start](https://user-images.githubusercontent.com/2542572/37280217-1fee972c-2628-11e8-91a3-3620415005ac.jpg)
![default](https://user-images.githubusercontent.com/2542572/37280221-236064ee-2628-11e8-8985-42e7930e66c0.jpg)

**Comment by noob-noob** [comment]
集群是通过appid进行分组，对于tomcat，appid为contextPath，当contextPath为"/"时则为部署的war包(或者文件夹)名。若图中各应用要分到不同的应用集群，需要更改部署的war包(或文件夹)名。

**Comment by gameboy120** [comment]
我看的现象是：appid是读取的web.xml的display-name，不同appid被归为一个应用集群。跟你说的有点不符合

**Comment by noob-noob** [comment]
display-name在UAV监控里作为对应用的描述（即appname），不作为区分不同应用的标识（即appid）。
