### ISSUE TITLE
日志、调用链路、服务降级需求

### ISSUE THREAD

**Issue by ZHANGGUOQING91** [uavorg/uavstack#30]
uav全体：
      您好，有以下三点需求，麻烦考虑加入到uavstack中，完善监控体系：
      1.目前在日志模块，无法通过以集群为单位，希望查询整个集群中所涉及的查询内容出现在哪几台实例上。这样可以更快速的定位问题，而不是仅仅通过每一个实例去查询。                                                          
      2.调用链路的提议：希望把traceId存放到业务日志中，这样就能从日志到调用链路，直接定位问题，整个一套的全维关联。通过关联traceID，能够准确定位调用链路，定位服务实例，定位集群、机器的问题。
      3.当定位到问题以后，能不能及时对发生异常的服务进行降级，或者在控制台进行实时降级，优化性能等操作。
      希望考虑以上三点需求，辛苦！

**Comment by uavstack** [comment]
Hi,

Thanks for submit requirements for us. 

we will discuss and please wait for conclusion.

**Comment by uavstack** [comment]
should we close this issue？
