### ISSUE TITLE
Application container data display of the time and space sandbox

### ISSUE THREAD

**Issue by BeliefYou8** [uavorg/uavstack#62]
新增时空沙盘应用容器以及进程的性能指标显示，修复ptag查询与拷贝的BUG
1.在选中一个应用实例后，增加显示其对应机器IP的性能指标与其进程的性能指标
2.在时空沙盘查询,BUG在于，进行大类性能指标查询时，不能根据ptag将指标分类显示，如查询RC，不能出现显示结果 修改要点：对ptag加上""查询，并对大类指标进行判断，成功显示RC，RC*等指标。
3.在时空沙盘同一组指标查询时，BUG在于，若同时查询具有ptag的指标与不含ptag的指标时，前者会覆盖掉后者的tags，如同时点击应用实例RC和count性能指标，只显示RC的性能指标，并未显示应用实例的count性能指标。 修改要点：在help.js的merge方法中，拷贝方法为浅拷贝，但对于tags而言，只一个对象，故必须对其进行特殊处理，进行深拷贝。

**Comment by noob-noob** [comment]
document  ready
