### ISSUE TITLE
外部应用通过接口查询数据

### ISSUE THREAD

**Issue by TideDlrow** [uavorg/uavstack#67]
目前文档中只是说明了外部应用可以通过类似http://ip:port/hb/query 的接口来获取相应的数据但是并没有详细的说明该用何种请求方式和请求参数才能得到正确的数据，能否提供一个相应的文档来说明这些接口的调用方式呢。当然不只是这个心跳的查询接口

**Comment by uavstack** [comment]
the issue is accepted. the documents should be ready in this month.

**Comment by noob-noob** [comment]
the interface document is ready, see https://uavorg.github.io/documents/uavdoc_architecture/healthmanager/jie-kou-shuo-ming.html, please check if it meets your needs
