### ISSUE TITLE
uav自身的依赖jar和项目里jar冲突

### ISSUE THREAD

**Issue by piaoyingfeimeng** [uavorg/uavstack#82]
是不是可以通过maven的shade把uav的依赖的jar和应用的jar区分开

**Comment by uavstack** [comment]
能否把具体冲突的详情说明一下。

关于shaded方案我们在早期实验的时候尝试过，依赖可见性的理想实现是OSGi的模式，也就是MOF需要见到应用的一些包，应用的某些类也要见到UAV的一些包（尽管感觉不出来），所以这个问题目前的办法是具体问题具体分析，具体解决。目前还没有即好又通用的做法。另外MOF是完全自研，三方依赖只有fastjson和fastscan，其余引入的类是应用里面的类，会用于画像，打hook等。

**Comment by piaoyingfeimeng** [comment]
javassist 这个jar的依赖，我自身的dubbo里也依赖了

**Comment by piaoyingfeimeng** [comment]
我已经解决了，在com.creditease.uav.monitorframework.buildComponent 这个项目里的pom里添加maven-shade-plugin插件
代码如下：
<properties>
		<version.plugin.shade>2.4.1</version.plugin.shade>
		<shade.javassist.source>javassist</shade.javassist.source>
		<shade.javassist.target>api.dependencies.javassist</shade.javassist.target>
	</properties>
在bulid里添加
<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>${version.plugin.shade}</version>
				<executions>
					<execution>
						<phase>install</phase>
						<goals>
							<goal>shade</goal>
						</goals>
						<configuration>
							<shadedArtifactAttached>false</shadedArtifactAttached>
							<createDependencyReducedPom>true</createDependencyReducedPom>
							<createSourcesJar>true</createSourcesJar>
							<shadeSourcesContent>true</shadeSourcesContent>
							<relocations>
								<relocation>
									<pattern>${shade.javassist.source}</pattern>
									<shadedPattern>${shade.javassist.target}</shadedPattern>
								</relocation>
							</relocations>
						</configuration>
					</execution>
				</executions>
			</plugin>
