### ISSUE TITLE
aredis-api-1.4.jar不存在

### ISSUE THREAD

**Issue by hnmas** [uavorg/uavstack#89]
AppHub的com.creditease.uav.console下面pom中定义依赖：
&lt;dependency&gt;
	&lt;groupId&gt;aredis.sourceforge.net&lt;/groupId&gt;
	&lt;artifactId&gt;aredis-api&lt;/artifactId&gt;
	&lt;version&gt;1.4&lt;/version&gt;
&lt;/dependency&gt;
这个依赖在各个maven仓库都找不到，在网上搜了下，只有一个：https://sourceforge.net/projects/aredis/files/
但这里只有：aredis-1.4.jar  没有：aredis-api-1.4.jar文件，是不是artifactId弄错了？

**Comment by uavstack** [comment]
HI,
在com.creditease.uav.cache.redis工程下的lib下面有aredis-api-1.4.jar

**Comment by hnmas** [comment]
找到了，我比了下aredis-api-1.4.jar和网上的aredis-1.4.jar，它们是同一个文件。

**Comment by hnmas** [comment]
建议改下依赖的artifactId，和文件的实际名称保持一致。

**Comment by uavstack** [comment]
Thanks for issue us!
