### ISSUE TITLE
指标的环比、同比预警

### ISSUE THREAD

**Issue by jdzwhy** [uavorg/uavstack#9]
是否能提供根据指标的环比、同比预警功能，比如在一个时间段内，当前一分钟订单总数比上一分钟下降了50%就预警

**Comment by uavstack** [comment]
thanks for submit issue for us, nice. we are under discussion now. please wait for conclusion.

**Comment by ZHANGGUOQING91** [comment]
mark

**Comment by uavstack** [comment]
Hi,
we decide to **release this feature to opensource version**. thanks for your requirement proposal.

we will annouce this feature when we are ready.

**Comment by uavstack** [comment]
this issue is done. should we close this issue?
