### ISSUE TITLE
请帮忙增加suse11 12的适配，目前网卡识别有问题。

### ISSUE THREAD

**Issue by christinkaka** [uavorg/uavstack#97]

**Comment by christinkaka** [comment]
现在遇到网卡解析有问题，ma启动连不上hm.

**Comment by uavstack** [comment]
we will take the adaption for suse. thanks for issue us.

**Comment by xxxllluuu** [comment]
fix by pull request https://github.com/uavorg/uavstack/pull/111 , you can try again

**Comment by christinkaka** [comment]
已解决
